name: Strange Stuff Store Ci

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
              java-version: '17'
              distribution: 'temurin'
              cache: maven
        - name: Test with Maven
          run: |
            cd strange_stuff_store
            mvn test
        - name: Upload test results as artifact
          uses: actions/upload-artifact@v4
          with:
            name: test-results
            path: strange_stuff_store/target/surefire-reports/
            
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
              java-version: '17'
              distribution: 'temurin'
              cache: maven
        - name: Build with Maven
          run: |
            cd strange_stuff_store
            mvn clean install

    notification:
        runs-on: ubuntu-latest
        env:
          MAIL_TO: airton.gabriel@ges.inatel.br
          MAIL_SUBJECT: Strange Stuff Store Building...
          MAIL_BODY: Your Build of Strange Stuff Store is running.
        steps:
          - uses: actions/checkout@v3
          - name: Notification 
            run: sh scripts/sendmail.sh
              

